"""Database storage module."""

from .database import get_session, init_db
from .models import (
    AlertSent,
    Base,
    EarningsDate,
    ETFHolding,
    InsiderTransaction,
    NewsItem,
    Price,
)
from .operations import (
    alert_exists_by_dedup_key,
    get_etf_holdings,
    get_insider_transactions,
    get_latest_price,
    get_prices,
    get_recent_alerts,
    get_recent_news,
    get_upcoming_earnings,
    get_unscored_news,
    insider_transaction_exists,
    news_exists,
    price_exists,
    save_alert,
    save_earnings_date,
    save_etf_holdings,
    save_insider_transaction,
    save_news_item,
    save_price,
    save_prices,
)

__all__ = [
    "init_db",
    "get_session",
    "Base",
    "Price",
    "InsiderTransaction",
    "NewsItem",
    "AlertSent",
    "EarningsDate",
    "ETFHolding",
    "save_price",
    "save_prices",
    "get_latest_price",
    "get_prices",
    "price_exists",
    "save_insider_transaction",
    "get_insider_transactions",
    "insider_transaction_exists",
    "save_news_item",
    "news_exists",
    "get_unscored_news",
    "get_recent_news",
    "save_alert",
    "get_recent_alerts",
    "alert_exists_by_dedup_key",
    "save_earnings_date",
    "get_upcoming_earnings",
    "save_etf_holdings",
    "get_etf_holdings",
]
