"""Research Queue Manager for managing pending deep research candidates.

This module manages which stock candidates are queued for deep research
report generation. The queue uses the StockCandidate model with status
"screening" to track candidates pending research.
"""

from loguru import logger
from sqlalchemy import select
from sqlalchemy.orm import Session

from ..storage import (
    CANDIDATE_STATUSES,
    StockCandidate,
    get_candidate_by_ticker,
    save_candidate,
)


class ResearchQueue:
    """Manages the queue of candidates pending deep research.

    The queue is based on StockCandidate status - candidates with status
    "screening" are considered in the queue. Priority is stored in
    composite_score (higher score = higher priority).

    This queue is used to prioritize which candidates receive deep research
    reports generated by Claude API, which has budget constraints.
    """

    # Status constants from CANDIDATE_STATUSES
    STATUS_DISCOVERED = CANDIDATE_STATUSES[0]  # "discovered"
    STATUS_SCREENING = CANDIDATE_STATUSES[1]  # "screening"

    def __init__(self, session: Session):
        """Initialize the research queue.

        Args:
            session: SQLAlchemy database session for queue operations
        """
        self.session = session

    def add_to_queue(self, ticker: str, priority: int = 0) -> bool:
        """Add a ticker to the research queue.

        If the ticker already exists as a candidate, updates its status to
        "screening" and sets the priority. If it doesn't exist, creates a
        new candidate.

        Args:
            ticker: Stock ticker symbol to add to queue
            priority: Priority score (stored as composite_score, higher = higher priority)

        Returns:
            True if successfully added/updated, False otherwise
        """
        try:
            # Check if candidate already exists
            candidate = get_candidate_by_ticker(self.session, ticker)

            if candidate:
                # Update existing candidate
                candidate.status = self.STATUS_SCREENING
                candidate.composite_score = float(priority)
                logger.info(
                    f"Updated {ticker} in research queue with priority {priority}"
                )
            else:
                # Create new candidate
                candidate = StockCandidate(
                    ticker=ticker,
                    status=self.STATUS_SCREENING,
                    composite_score=float(priority),
                    discovery_source="research_queue",
                )
                save_candidate(self.session, candidate)
                logger.info(
                    f"Added {ticker} to research queue with priority {priority}"
                )

            self.session.flush()
            return True

        except Exception as e:
            logger.error(f"Failed to add {ticker} to research queue: {e}")
            return False

    def get_next(self) -> StockCandidate | None:
        """Get the highest priority candidate from the queue.

        Returns the candidate with status "screening" and the highest
        composite_score.

        Returns:
            StockCandidate with highest priority, or None if queue is empty
        """
        stmt = (
            select(StockCandidate)
            .where(StockCandidate.status == self.STATUS_SCREENING)
            .order_by(StockCandidate.composite_score.desc())
            .limit(1)
        )

        candidate = self.session.scalar(stmt)

        if candidate:
            logger.debug(
                f"Next in queue: {candidate.ticker} "
                f"(priority: {candidate.composite_score})"
            )
        else:
            logger.debug("Research queue is empty")

        return candidate

    def get_queue(self, limit: int = 20) -> list[StockCandidate]:
        """Get list of candidates in the queue ordered by priority.

        Args:
            limit: Maximum number of candidates to return (default: 20)

        Returns:
            List of StockCandidate objects ordered by priority (highest first)
        """
        stmt = (
            select(StockCandidate)
            .where(StockCandidate.status == self.STATUS_SCREENING)
            .order_by(StockCandidate.composite_score.desc())
            .limit(limit)
        )

        candidates = list(self.session.scalars(stmt))

        logger.debug(f"Retrieved {len(candidates)} candidates from research queue")
        return candidates

    def remove_from_queue(self, ticker: str) -> bool:
        """Remove a ticker from the research queue.

        Updates the candidate's status from "screening" back to "discovered".

        Args:
            ticker: Stock ticker symbol to remove from queue

        Returns:
            True if successfully removed, False if ticker not found
        """
        candidate = get_candidate_by_ticker(self.session, ticker)

        if candidate is None:
            logger.warning(f"Cannot remove {ticker}: not found in database")
            return False

        if candidate.status != self.STATUS_SCREENING:
            logger.warning(
                f"Cannot remove {ticker}: status is '{candidate.status}', "
                f"not '{self.STATUS_SCREENING}'"
            )
            return False

        candidate.status = self.STATUS_DISCOVERED
        self.session.flush()

        logger.info(f"Removed {ticker} from research queue")
        return True
